name: Golang Release

on:
  push:
    branches:
      - main

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: go mod tidy
      - run: go run .
      - run: GOPROXY=proxy.golang.org go list -m gitlab.com/safeutils/gitlab-profile@0.0.1
